#include "global.h"
#include "constants/items.h"
#include "constants/flags.h"
#include "script.h"
#include "item.h"
#include "overworld.h"

// Check if player is currently in Kanto region
static bool8 IsPlayerInKantoRegion(void)
{
    // Check if current map is in Kanto map group
    // MAP_GROUP_KANTO should be generated by the build system
    // For now, we'll use a hardcoded value (assuming Kanto is map group 8)
    return (gSaveBlock1Ptr->location.mapGroup == 8);
}

// Generic HM check function
static bool8 CanUseHMInRegion(u16 hmItem, u16 hoennFlag, u16 kantoFlag)
{
    // Check if player has the HM
    if (!CheckBagHasItem(hmItem, 1))
        return FALSE;
    
    // Check current region and apply appropriate rules
    if (IsPlayerInKantoRegion())
    {
        // In Kanto: Must have Kanto-specific flag
        return CheckFlag(kantoFlag);
    }
    else
    {
        // In Hoenn: Can use if obtained in Hoenn
        return CheckFlag(hoennFlag);
    }
}

// Individual HM check functions
bool8 CanUseHM01Cut(void)
{
    return CanUseHMInRegion(ITEM_HM01, FLAG_HM01_OBTAINED_IN_HOENN, FLAG_HM01_OBTAINED_IN_KANTO);
}

bool8 CanUseHM02Fly(void)
{
    return CanUseHMInRegion(ITEM_HM02, FLAG_HM02_OBTAINED_IN_HOENN, FLAG_HM02_OBTAINED_IN_KANTO);
}

bool8 CanUseHM03Surf(void)
{
    return CanUseHMInRegion(ITEM_HM03, FLAG_HM03_OBTAINED_IN_HOENN, FLAG_HM03_OBTAINED_IN_KANTO);
}

bool8 CanUseHM04Strength(void)
{
    return CanUseHMInRegion(ITEM_HM04, FLAG_HM04_OBTAINED_IN_HOENN, FLAG_HM04_OBTAINED_IN_KANTO);
}

bool8 CanUseHM05Flash(void)
{
    return CanUseHMInRegion(ITEM_HM05, FLAG_HM05_OBTAINED_IN_HOENN, FLAG_HM05_OBTAINED_IN_KANTO);
}

bool8 CanUseHM06RockSmash(void)
{
    return CanUseHMInRegion(ITEM_HM06, FLAG_HM06_OBTAINED_IN_HOENN, FLAG_HM06_OBTAINED_IN_KANTO);
}

bool8 CanUseHM07Waterfall(void)
{
    return CanUseHMInRegion(ITEM_HM07, FLAG_HM07_OBTAINED_IN_HOENN, FLAG_HM07_OBTAINED_IN_KANTO);
}

bool8 CanUseHM08Dive(void)
{
    return CanUseHMInRegion(ITEM_HM08, FLAG_HM08_OBTAINED_IN_HOENN, FLAG_HM08_OBTAINED_IN_KANTO);
}

// Function to get appropriate HM restriction message
const u8* GetHMRegionRestrictionMessage(u16 hmItem)
{
    if (IsPlayerInKantoRegion())
    {
        return gText_HMNotUsableInKanto;
    }
    else
    {
        return gText_HMNotUsableInHoenn;
    }
}

// Function to set HM obtained flag for current region
void SetHMObtainedInCurrentRegion(u16 hmItem)
{
    u16 flagId;
    
    // Determine which flag to set based on HM and current region
    if (IsPlayerInKantoRegion())
    {
        // Set Kanto flag
        switch (hmItem)
        {
        case ITEM_HM01: flagId = FLAG_HM01_OBTAINED_IN_KANTO; break;
        case ITEM_HM02: flagId = FLAG_HM02_OBTAINED_IN_KANTO; break;
        case ITEM_HM03: flagId = FLAG_HM03_OBTAINED_IN_KANTO; break;
        case ITEM_HM04: flagId = FLAG_HM04_OBTAINED_IN_KANTO; break;
        case ITEM_HM05: flagId = FLAG_HM05_OBTAINED_IN_KANTO; break;
        case ITEM_HM06: flagId = FLAG_HM06_OBTAINED_IN_KANTO; break;
        case ITEM_HM07: flagId = FLAG_HM07_OBTAINED_IN_KANTO; break;
        case ITEM_HM08: flagId = FLAG_HM08_OBTAINED_IN_KANTO; break;
        default: return;
        }
    }
    else
    {
        // Set Hoenn flag
        switch (hmItem)
        {
        case ITEM_HM01: flagId = FLAG_HM01_OBTAINED_IN_HOENN; break;
        case ITEM_HM02: flagId = FLAG_HM02_OBTAINED_IN_HOENN; break;
        case ITEM_HM03: flagId = FLAG_HM03_OBTAINED_IN_HOENN; break;
        case ITEM_HM04: flagId = FLAG_HM04_OBTAINED_IN_HOENN; break;
        case ITEM_HM05: flagId = FLAG_HM05_OBTAINED_IN_HOENN; break;
        case ITEM_HM06: flagId = FLAG_HM06_OBTAINED_IN_HOENN; break;
        case ITEM_HM07: flagId = FLAG_HM07_OBTAINED_IN_HOENN; break;
        case ITEM_HM08: flagId = FLAG_HM08_OBTAINED_IN_HOENN; break;
        default: return;
        }
    }
    
    SetFlag(flagId);
}
